Homepage draft
shyama12/booksgalore pull request #4
Opened 2022-11-03 20:36 UTC by Sebastir

Added the typed.js effect + background image with the call to action

2022-11-03 22:32 UTC, shyama12 requested changes

2022-11-03 22:32 UTC, shyama12 commented on app/javascript/controllers/typed_controller.js
> +    console.log("working connection from Controller")
Is it better that we remove this line?

2022-11-04 07:34 UTC, Sebastir commented on app/javascript/controllers/typed_controller.js
> +    console.log("working connection from Controller")
Yes, Agree! :)

2022-11-04 07:35 UTC, Sebastir commented
Removing boilerplate code

2022-11-04 07:35 UTC, merged